    <div>
      <a href="https://avsbq.org">🏠</a> |
      <a href="https://archive.avsbq.org">🗃️</a> |
      <a href="https://mal.avsbq.org">👿</a> |
      <a href="https://language.avsbq.org">🌐</a> |
      <a href="https://link.avsbq.org">🔗</a> |
      <a href="https://iconography.avsbq.org">🖌️</a> |
      <a href="https://project.avsbq.org">🏗️</a> |
      <a href="https://tutorial.avsbq.org">🛠️</a> |
      <a href="https://video.avsbq.org">📹</a> |
	<a href="https://cn.avsbq.org">🀄️
</a> |
	<a href="https://bn.avsbq.org">🇧🇩</a>
    </div>

<div><a href="https://avsbq.org/.contact">📞</a> - <a href="https://avsbq.org/.donate">💰</a> - <a href="https://profile.avsbq.org">💼</a></div>
