    <div>
      <a href="https://avsbq.org">HOME</a> |
      <a href="https://arc.avsbq.org"><span style="color: red;"><b>ARCHIVE</b></span></a> |
      <a href="https://ico.avsbq.org">ICONs</a> |
      <a href="https://mal.avsbq.org">MAL !<a> |
      <a href="https://lang.avsbq.org">LANG.</a> |
      <a href="https://lnk.avsbq.org">LINKs</a> |
      <a href="https://todo.avsbq.org">TO-DO</a> |
      <a href="https://hbk.avsbq.org">HANDBOOK</a> 
    </div>

<div><a href="https://avsbq.org/.reach">REACH</a> - <a href="https://avsbq.org/.give">GIVE</a> - <a href="/sitemap">SITEMAP</a>
<br>
<input type="text" id="searchBar" placeholder="Search...">
<div id="searchResults"></div>
<script src="https://arc.avsbq.org/s.js"></script>
</div>
